### ISSUE TITLE
Primary event times (p) definition within function call unclear from first look at the docs

### ISSUE THREAD

**Issue by jcblemai** [epinowcast/primarycensoreddist#107]
**Describe the bug**
In the main documentation, [here](https://primarycensoreddist.epinowcast.org/articles/primarycensoreddist.html), we have the mention of an $f_p$ distribution that generates the primary event times. As this distribution is not explicitly shown or mentioned in the code snippet below, there is some confusion about how to set it put (and I ended up assuming the first arguments of [rprimarycensoreddist](https://primarycensoreddist.epinowcast.org/reference/rprimarycensoreddist.html) was this $f_p$, but no, it was the delay distribution. I

**To Reproduce**
1. Go to the documentation, and try to match the described distribution to the function call below.

**Expected behavior**
Either an explicit set of this distribution within the function call, or a comment that the default argument is uniform and that it is not shown there.

**Comment by seabbs** [comment]
Thanks for the this @jcblemai and hope you got home safely! 

Any chance you would like to have a go at a PR to improve the clarity of this? No worries if not. 

I think the fix is to directly the the primary event distributions as arguments in the code blocks rather than depend on the defaults?

**Comment by seabbs** [comment]
Closed by #122
