### ISSUE TITLE
primarycensoreddist -> primarycensored

### ISSUE THREAD

**Issue by seabbs** [epinowcast/primarycensoreddist#108]
We now have a Julia version of this tool that is called `PrimaryCensored` to fit with the naming approach take in `Distributions.jl` does this mean we should consider renaming this to `primarycensored` (and so renaming all the functions that currently use `dist` as well or are we happy with these having slightly different names?

**Comment by athowes** [comment]
I prefer shorter version and think `primarycensoreddist` is a mouthful.

**Comment by seabbs** [comment]
This doesn't introduce a docs clash as the julia tooling is moving to `PrimaryCensored.EpiAware.org`

**Comment by athowes** [comment]
Regarding this sorry if this is something I've brought up before but I find the focus on "primary" censoring over censoring in general to be confusing.

I am using `primarycensoreddist` functions for double censored observation processes. Am I wrong to do so?

(I mention this as it relates to the name. Something like `censordist` seems cleaner and leave more options in future to expand into "not only primary censored".)

**Comment by seabbs** [comment]
its because the primary censoring is the special bit and the secondary censoring is the same as everything else. The point is that solving primary censoring is the challenge and the only new concept people need to worry about.

**Comment by athowes** [comment]
I think the exact technical details of the challenge matter more to developers than they do to users. Ultimately this solves both primary and secondary censoring. I expect most people will not be aware of this background.

**Comment by seabbs** [comment]
I don't think I totally agree but happy to see a new issue

**Comment by seabbs** [comment]
I think the current conclusion is yes we should do this so moving from a question to issue. We need to: 

- [ ] Find and replace the package name everywhere
- [ ] Look for `dist` naming and change to match dropping this from the name of the package
- [ ] Change the repository name
- [ ] Change the redirect on square space (@seabbs)
- [ ] Add a redirect to link from the current web docs to the new one.
- [ ] Add a news item communication this breaking change.
