### ISSUE TITLE
rprimarycensoreddist: Censor and truncate or truncate and censor

### ISSUE THREAD

**Issue by seabbs** [epinowcast/primarycensoreddist#23]
As the title I think the order that these take place is matters in some settings (as observation should I think be based on the continuous distribution and not the secondary event censored one). 

That is the reverse of what we currently have (and what we have been doing historically). I think in most of the settings we have been considered (where D is a multiple of the secondary event window) the ordering doesn't matter and so perhaps that explains why this hasn't come up.

**Comment by seabbs** [comment]
@athowes any thoughts on this?

**Comment by athowes** [comment]
(I vaguely get that there might be a difference depending on whether you censor first or truncate first but don't have any good thoughts about it.)
