### ISSUE TITLE
`simulate_double_censored_pmf()`  could enforce a sum-to-one

### ISSUE THREAD

**Issue by zsusswein** [epinowcast/primarycensoreddist#3]
**Describe the issue**

When using `simulate_double_censored_pmf()` as of `d4a65aa`, the returned vector does not necessarily sum to one. Instead, it sums to the quantile of the max with some numerical error.

**To Reproduce**

```{r}
set.seed(123456)

meanlog <- 2
sdlog <- 0.5

pmf <- epinowcast::simulate_double_censored_pmf(
                            max = 12,
                            fun_primary = runif,
                            fun_dist = rlnorm,
                            n = 1e6,
                            meanlog = meanlog,
                            sdlog = sdlog
                    )
print(pmf) # 0.000003 0.001166 0.015477 0.052620 0.092002 0.115490 0.121315 0.113358 0.098575 0.082034 0.066422 0.052999 0.041724
print(sum(pmf)) # 0.853185
print(abs(sum(pmf) - 1)) # 0.146815
```

**Expected behavior**

Because the function name and description refer to the returned vector as a PMF, I would expect it to sum to one. The example here is a bit contrived because a max of 12 is much too low (right around the 85.3rd percentile), but this behavior persists with higher/more realistic maximums.

More generally, I would expect the vector returned from `simulate_double_censored_pmf()` to be able to be passed immediately to `enw_expectation_module(generation_time = pmf, ...)`. But because the returned vector doesn't sum to one, [this process throws an error](https://github.com/epinowcast/epinowcast/blob/d4a65aad2735be7ffa08ca605f979346f62e4212/R/model-modules.R#L341C1-L343C4).

**Desktop (please complete the following information):**
 - OS: Windows 10, v22H2
 - Version: `{epinowcast}` dev build as of commit `d4a65aa` (latest commit on main on 2023-11-16)

**Comment by seabbs** [comment]
I think this has been dealt with/ is no longer relevant due to the inbuilt support for truncation at all levels (via D). Kick the tires and feel free to reopen if you disagree
