### ISSUE TITLE
Add support for analytical solutions

### ISSUE THREAD

**Issue by seabbs** [epinowcast/primarycensoreddist#32]
Quite a few of the distributions we are using have analytical solutions which could be used instead of the numerically solved integral. Examples include the exponential and gamma for the uniform primary event distribution case. 

Performance wise it likely makes sense to use these analytical solutions where available and have a framework for adding new ones as they come available. 

I think this would look like: 

- [x] A new @family for analytical solutions
- [x] A argument to pass in R to use the analytical solutions if available (and default to true)
- [ ] To avoid to much user facing args I am tempted to say we should just use the analytical solutions in stan directly but doing this would need some experimentation to make sure the auto-diff is okay.

**Comment by seabbs** [comment]
I think that this might prove difficult for most distribution combinations unfortunately even in the simple case with no truncation.

**Comment by seabbs** [comment]
@jbracher suggests thinking about this using moment generating functions -> a couple of moments -> finding a distribution that matches with that.

**Comment by seabbs** [comment]
I'm not sure how we could really go about doing this in stan though as we would need to match moments

**Comment by SamuelBrand1** [comment]
@seabbs Is this approach being superceded in #90 ?
