### ISSUE TITLE
Review why it works

### ISSUE THREAD

**Issue by seabbs** [epinowcast/primarycensoreddist#83]
I spoke to @parksw3 a bit about this and if interested a review of the why it works sections would be great.

**Comment by parksw3** [comment]
> In order to reason upon the distribution of the censored delay time $T_c$, it is useful to consider the time from the end (right) point of the primary censoring interval to the secondary time as a random variable,
> 
> $$
> S_+ = S - (t_P + w_P) = T - ((t_P + w_P) - P) = T - C_P.
> $$
> 
> Where $T$ is the delay distribution of interest and $C_P = (t_P + w_P) - P$ is interval between the end (right) point of the primary censoring window and the primary event time; note that by definition $C_P$ is not observed but we can relate its distribution to the distribution of $P$: $F_{C_P}(p) = Pr(C_P < p) = Pr(P > w_P - p)$.
> 

I'm confused about the last equation. Maybe I'm missing something obvious here. Shouldn't the last equation be: 

$F_{C_P}(p) = Pr(C_P < p) = Pr((t_P + w_P) - P < p) = Pr(P > t_P + w_P - p)$?

It looks like it's missing t_P?

**Comment by parksw3** [comment]
The use of integration by part is very neat. And so I'm guessing we can do the same with the derivation in the long paper, which might give slightly simpler notation and consistency?

Starting from here:

$$
\begin{aligned}
\mathrm{P}(S_L < S < S_R | P_L < P < P_R) &= \frac{\mathrm{P}(P_L < P < P_R, S_L < S < S_R)}{\mathrm{P}(P_L < P < P_R)} \\
   &= \frac{\int_{P_L}^{P_R} \int_{S_L}^{S_R} g_P(x) f_x(y-x) dy dx}{\int_{P_L}^{P_R} g_P(x) dx}\\
   &= \int_{P_L}^{P_R} \int_{S_L}^{S_R} g_P(x|P_L, P_R) f_x(y-x)dy dx
\end{aligned}
$$

If we assume that the forward distribution doesn't vary over time (such that $f_x = f$), then

$$
\int_{P_L}^{P_R} \int_{S_L}^{S_R} g_P(x|P_L, P_R) f_x(y-x)dy dx = \int_{P_L}^{P_R} g_P(x|P_L, P_R) \big[F(S_L - x) - F(S_R - x)\big] dx
$$


Then, by using integration by parts, we get:

$$
\int_{P_L}^{P_R} g_P(x|P_L, P_R) \big[F(S_L - x) - F(S_R - x)\big] dx = ...
$$

hold on... will be back...

**Comment by SamuelBrand1** [comment]
> It looks like it's missing t P ?

Yes! Thats a typo (I think, I'll just double check myself)
