### ISSUE TITLE
Check why it works for maths lines we can do without

### ISSUE THREAD

**Issue by seabbs** [epinowcast/primarycensoreddist#84]
I.e in the analytical solutions there are a few substitutions where we first write out the full equation vs just subbing in our already solved component chunks. The fear is this might be confusing to readers and might not really add much. Based on #68

**Comment by seabbs** [comment]
Refers to this: https://github.com/epinowcast/primarycensoreddist/pull/68#discussion_r1765260060

and similar. 

Potentially this can be reviewed along side #72

**Comment by seabbs** [comment]
@SamuelBrand1 did you catch this in your PR? I think no?

**Comment by SamuelBrand1** [comment]
No.

Maybe @parksw3 could give a bit of feedback? I'm possible a bit too close to decide what reads well/ is useful vs not!

**Comment by parksw3** [comment]
Sorry for the confusion, but should I read the math or code? If you could point me to where to look, that would be helpful...

**Comment by seabbs** [comment]
The maths. The link is to the Rmd doc so we can get the line number 2017

**Comment by seabbs** [comment]
Essentially it boils down to should we get rid of the first term in 3.9 because we actually arrive at the second line by subbing the components we have just derived into the last line of 3.5

**Comment by seabbs** [comment]
Lack of traction here. As this is relatively easy to close shall we either PR a quick change or close this as won't do

**Comment by SamuelBrand1** [comment]
Hey @seabbs . I think there is a tension here because we also want to be clear... replication not necessarily bad in the maths.

**Comment by seabbs** [comment]
My point is that I think in these instances it is unclear as it adds additional lines of maths for readers to take in that don't actually advance the argument and aren't clearly signposted
