### ISSUE TITLE
Why it works: Link each section in 3.1 to the section it relates to in the getting started w/ how

### ISSUE THREAD

**Issue by seabbs** [epinowcast/primarycensoreddist#91]
See title

**Comment by seabbs** [comment]
@SamuelBrand1 what do you think? Target at the same time as #72 ?

**Comment by SamuelBrand1** [comment]
Yeah good shout!

**Comment by parksw3** [comment]
I think the math I put down here "proves" the equivalence in case it's useful...: https://github.com/epinowcast/primarycensoreddist/issues/83
